FROM node:16-alpine as web_build
WORKDIR /web
COPY ./src/frontend/ .
RUN npm install pnpm -g && \
    pnpm install --registry=https://registry.npm.taobao.org
RUN npm run build

FROM python:3.10-slim-buster
# 设置环境变量
ENV DATABASE_HOSTNAME="10.20.148.81"
ENV DATABASE_PORT="3306"
ENV DATABASE_USER="app_scheduler"
# web静态文件的路径
ENV STATIC_DIR="./web/dist"
WORKDIR /appscheduler
COPY --from=web_build /web/dist ./web/dist
COPY ./requirements.txt .
RUN python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt
COPY ./src/backend ./src/backend
COPY ./bin ./
CMD ["python3", "./run.py"]
