FROM node:20-alpine as web_build
WORKDIR /web
COPY ./src/frontend/ .
RUN npm install pnpm -g --registry=https://registry.npmmirror.com && \
    pnpm install --registry=https://registry.npmmirror.com
RUN pnpm run build

FROM python:3.10-slim-buster
WORKDIR /appscheduler
# web静态文件的路径
ENV STATIC_DIR="./web/dist"
# 系统存储文件路径
ENV FILES_DIR="./files"
# pip源
ENV PIP_INDEX_URL="https://mirrors.aliyun.com/pypi/simple/"
COPY --from=web_build /web/dist ./web/dist
COPY ./requirements.txt .
# RUN cat > /etc/apt/sources.list << EOF \
#     deb http://mirrors.163.com/debian/ buster main contrib non-free \
#     deb http://mirrors.163.com/debian/ buster-updates main contrib non-free \
#     deb http://mirrors.163.com/debian/ buster-backports main contrib non-free \
#     deb http://mirrors.163.com/debian-security buster/updates main contrib non-free \
#     EOF && \
#     cat /etc/apt/sources.list && \
#     apt-get update && \
#     apt-get install -y --no-install-recommends wget && \
#     python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt
RUN python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt

COPY ./src/backend ./src/backend
COPY ./bin ./
CMD ["python3", "./run.py"]
